name: Conda Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          activate-environment: scipy
          python-version: 3.9

      - name: Install conda packages
        shell: pwsh
        run: |
          conda install scipy metpy

      - name: Hello World 
        shell: pwsh
        run: |
          python -c "import scipy as sp; print('Scipy version: '+sp.__version__)"


